version: '3.5'
services:
  scraper:
    build: .
    environment:
      - CONFIG_FILE=/config/config.json
      - DATABASE_PATH=sqlite:////data/exchanges_db.sqlite
    volumes:
      - ./data:/data
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  metabase-app:
    build:
      context: build_metabase
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - ./:/metabase-data
      - ./data:/data
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_INIT_SQL_FILE: /metabase-data/metabase.db.sql
      MB_DB_SAVE_TO_SQL_FILE: /metabase-data/metabase.db.sql
    networks:
      - metanet1
    depends_on:
      - scraper
networks:
  metanet1:
    driver: bridge
