SET DB_CLOSE_DELAY -1;
TRUNCATE TABLE "PUBLIC"."TASK_HISTORY";
DELETE FROM "PUBLIC"."ACTIVITY" WHERE "TOPIC" != 'install';
TRUNCATE TABLE "PUBLIC"."QUERY_EXECUTION";
TRUNCATE TABLE "PUBLIC"."VIEW_LOG";
